### ISSUE TITLE
Repository rename broke URL references

### ISSUE THREAD

**Issue by TimMoore** [lightbend/console-charts#214]
While we have been trying to update old references to https://lightbend.github.io/helm-charts, some still remain (including some on third-party web sites that are out of our control). If we can avoid breaking this URL, it would be better.

Renaming this repository from `helm-charts` to `console-charts` seems to have broken the old URL, as GitHub pages isn't redirecting automatically from https://lightbend.github.io/helm-charts/index.yaml to https://lightbend.github.io/console-charts/index.yaml

**Comment by jsravn** [comment]
I assume this is for the "reactive-sandbox" chart? I suggest we create a repo for it to preserve the old behavior.

Some more info at https://shoehornwithteeth.com/ramblings/2016/12/redirecting-github-pages-after-renaming-a-repository/.

**Comment by jsravn** [comment]
Alright, I've added reactive-sandbox back now. I created https://github.com/lightbend/lightbend.github.io and added a helm-charts directory with the  reactive sandbox charts and index.yaml.

**Comment by jsravn** [comment]
@TimMoore can you confirm it's working as expected now?

**Comment by TimMoore** [comment]
LGTM. Thanks, @jsravn!
